### ISSUE TITLE
Pings become synchronized after a while

### ISSUE THREAD

**Issue by patrakov** [lynxthecat/cake-autorate#24]
The code initially tries to "Space out pings by ping interval / number of reflectors". However, this spacing-out does not persist. After the night, the pings became almost 100% synchronized, thus losing the temporal resolution:

```
1649738354.339253 1      3      0   1   [1649738354.247817] 9.9.9.9         8421   29457  38400  8951   0 idle           idle           556    163    -64    -96    1.2    -12.5 
1649738354.422146 1      3      0   1   [1649738354.258872] 1.1.1.1         8422   57339  57600  261    0 idle           idle           556    163    -64    -96    1.2    -12.5 
1649738354.506180 1      3      0   1   [1649738354.264873] 8.8.4.4         8421   53699  55700  2003   0 idle           idle           556    163    -64    -96    2.2    -12.5 
1649738354.589174 1      3      0   1   [1649738354.275154] 8.8.8.8         8421   60394  65800  5411   0 idle           idle           556    163    -64    -96    2.2    -12.5 
1649738358.336279 110    12     19  7   [1649738358.248908] 9.9.9.9         8422   29463  35600  6143   0 low            idle           544    166    -64    -98    2.2    -14.5 
1649738358.437099 110    12     20  7   [1649738358.263852] 1.1.1.1         8423   57340  58700  1361   0 low            idle           544    166    -64    -98    2.2    -14.5 
1649738358.519066 110    12     20  7   [1649738358.273839] 8.8.8.8         8422   60394  60700  306    0 low            idle           544    166    -64    -98    0.2    -14.5 
1649738358.601200 110    12     20  7   [1649738358.276845] 8.8.4.4         8422   53708  63400  9701   0 low            idle           544    166    -64    -98    0.2    -14.5 
1649738362.349216 4      3      0   1   [1649738362.258866] 9.9.9.9         8423   29474  41400  11937  0 idle           idle           544    166    -65    -98    2.2    -12.5 
1649738362.431115 4      3      0   1   [1649738362.267916] 1.1.1.1         8424   57341  58800  1460   0 idle           idle           544    166    -65    -98    2.2    -12.5 
1649738362.514163 4      3      0   1   [1649738362.278377] 8.8.8.8         8423   60394  61200  806    0 idle           idle           544    166    -65    -97    0.2    -12.5 
1649738362.595243 4      3      0   1   [1649738362.276988] 8.8.4.4         8423   53713  59600  5892   0 idle           idle           544    166    -65    -97    0.2    -12.5 
1649738366.357298 12     16     2   9   [1649738366.259868] 9.9.9.9         8424   29482  38400  8926   0 idle           idle           533    169    -64    -97    3.2    -13.5 
1649738366.459498 12     16     2   9   [1649738366.271022] 1.1.1.1         8425   57341  57900  559    0 idle           idle           533    169    -64    -97    3.2    -13.5 
1649738366.541186 12     16     2   9   [1649738366.285891] 8.8.8.8         8424   60398  64600  4206   0 idle           idle           533    169    -63    -98    2.2    -14.5 
1649738366.625145 12     16     2   9   [1649738366.288897] 8.8.4.4         8424   53726  67300  13587  0 idle           idle           533    169    -63    -98    2.2    -14.5 
1649738370.351141 159    110    29  65  [1649738370.260978] 9.9.9.9         8425   29488  35600  6118   0 medium         medium         533    169    -61    -94    4.2    -13.5 
1649738370.436131 159    110    29  65  [1649738370.275232] 1.1.1.1         8426   57341  58100  759    0 medium         medium         533    169    -61    -94    4.2    -13.5 
1649738370.521240 159    110    29  65  [1649738370.285985] 8.8.8.8         8425   60398  60800  402    0 medium         medium         533    169    -62    -95    0.2    -12.5 
1649738370.603143 159    110    29  65  [1649738370.290986] 8.8.4.4         8425   53737  65500  11774  0 medium         medium         533    169    -62    -95    0.2    -12.5 
1649738374.361174 291    31     54  18  [1649738374.268897] 9.9.9.9         8426   29497  39400  9912   0 medium         idle           533    172    -63    -96    4.2    -13.5 
1649738374.453875 291    31     54  18  [1649738374.281093] 1.1.1.1         8427   57341  57900  559    0 medium         idle           533    172    -63    -96    4.2    -13.5 
1649738374.537167 291    31     54  18  [1649738374.287952] 8.8.4.4         8426   53741  58600  4863   0 medium         idle           533    172    -64    -97    4.2    -13.5 
1649738374.619121 291    31     54  18  [1649738374.290958] 8.8.8.8         8426   60399  61800  1402   0 medium         idle           533    172    -64    -97    4.2    -13.5 
```

(The last four columns are signal strength measurements due to a local modification, please ignore, actually only the timestamps in the first column are relevant).

The suspected cause is that the ping processes were put to sleep, and there is nothing that restores the spacing-out when sending SIGCONT.

**Comment by lynxthecat** [comment]
Fantastic spot! Endeavouring to keep the spacing is indeed important and that they become synchronised is hugely detrimental for the reason that you state: we lose granularity. 

I thought sending 'kill -STOP' and 'kill -CONT' would be fine because I imagined it being exactly like pausing and resuming the processes that had already been started in a staggered manner. But hopefully I am mistaken because the fix then would be easy - just stagger the 'kill -CONT' commands in the same way as the ping commands were staggered. 

The latter would have the added benefit of resetting the staggering, which would have always tended to drift somewhat anyway. 

So I'll try this and let's see if it fixes this issue.

**Comment by lynxthecat** [comment]
@moeller0 I am intrigued and a little stumped by how to tackle this one. 

I tested by setting:

```
reflector_ping_interval_s=4 # (seconds, e.g. 0.2s or 2s)
sustained_idle_sleep_thr_s=6  # time threshold to put pingers to sleep on sustained dl/ul achieved rate < idle_thr (seconds)
```

with my usual four reflectors, and having the pingers get repeatedly put to sleep and woken up as per:

https://github.com/lynxthecat/CAKE-autorate/blob/main/CAKE-autorate.sh#L347

However I see the 1s spacing retained:

[ping_sync.txt](https://github.com/lynxthecat/CAKE-autorate/files/8471428/ping_sync.txt)

so it seems the solution to @patrakov's observation that with time his ping responses become synchronized is not as simple as I had imagined/hoped, i.e. by repeating this:

https://github.com/lynxthecat/CAKE-autorate/blob/main/CAKE-autorate.sh#L230

for the 'kill -CONT' calls.

Admittedly this is a benefit of 'fping', namely that 'fping' facilitates improved control over the spacing between pings because it pings in round robin and so the spacing is guaranteed to remain. 

And yet use of 'fping' reduces our flexibility in controlling individual ping streams (e.g. we have to shut the whole fping process down just to remove one reflector, whereas with iputils-ping we can just shut down the one naughty stream).

So it would be nice if we could improve the separation somehow. 

Any ideas? Now I know that just staggering the start-time of the calls is not guaranteed to ensure long term spacing, but I thought random jitter would be fine. So perhaps there is an easy fix here to help ameliorate things. Also, a more drastic solution would be to periodically look at the response timestamps and stop and start individual ping streams to forcibly restore spacing.

**Comment by lynxthecat** [comment]
Makes sense to me. One challenge is how to addres retention of the background process id. Right now I retain the ping pid: 

https://github.com/lynxthecat/CAKE-autorate/blob/97bba64a129b433bc2c75d501a0ed4d5d20be47f/CAKE-autorate.sh#L150

I kill that and that effectively kills the background monitor_reflector_path process. 

But now if the monitor_reflector_path process restarts pings then I think I ideally just want pid for the monitor_reflector_path proceed that I can kill, which in turn will kill the ping. I don't entirely understand the 'exec' call. Would running ping with 'exec' inside the function mean that killing the pid for the function will kill the function and ping?

**Comment by moeller0** [comment]
> Makes sense to me. One challenge is how to address retention of the background process id. Right now I retain the ping pid:
> 
> https://github.com/lynxthecat/CAKE-autorate/blob/97bba64a129b433bc2c75d501a0ed4d5d20be47f/CAKE-autorate.sh#L150
> 
> We kill that and that effectively kills the background monitor_reflector_path process.
> 
> But now if the monitor_reflector_path process restarts pings then I think we ideally just want pid for the monitor_reflector_path process that we can kill, which in turn will kill the ping. I don't entirely understand the 'exec' call. Would running ping with 'exec' inside the function mean that killing the pid for the function will kill the function and ping?

One option is to move this into its own file again, so the background PID then addresses the bash script, which can handle the stopping/restarting of the ping binary on its own, no? Similar to what you propose... I guess it is a matter of taste, but moving the monitor_reflector_path into its own set of files/scripts seems helpful to clean things up a bit, given that you will be adding more code to this function making the main script harder to read?

**Comment by lynxthecat** [comment]
Hmm, interesting. Here is what I see from my RT3200:

```
root@OpenWrt:~# ping -D -v -n -i 2 8.8.8.8 & sleep 1 ; ping -D -v -n -i 2 8.8.4.4 & wait
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
[1649761995.527296] 64 bytes from 8.8.8.8: icmp_seq=1 ttl=114 time=56.6 ms
PING 8.8.4.4 (8.8.4.4) 56(84) bytes of data.
[1649761996.518335] 64 bytes from 8.8.4.4: icmp_seq=1 ttl=114 time=44.0 ms
[1649761997.519758] 64 bytes from 8.8.8.8: icmp_seq=2 ttl=114 time=45.8 ms
[1649761998.529602] 64 bytes from 8.8.4.4: icmp_seq=2 ttl=114 time=52.3 ms
[1649761999.519421] 64 bytes from 8.8.8.8: icmp_seq=3 ttl=114 time=44.7 ms
[1649762000.528385] 64 bytes from 8.8.4.4: icmp_seq=3 ttl=114 time=48.5 ms
[1649762001.520522] 64 bytes from 8.8.8.8: icmp_seq=4 ttl=114 time=42.8 ms
[1649762002.519512] 64 bytes from 8.8.4.4: icmp_seq=4 ttl=114 time=36.9 ms
[1649762003.519566] 64 bytes from 8.8.8.8: icmp_seq=5 ttl=114 time=39.6 ms
[1649762004.529443] 64 bytes from 8.8.4.4: icmp_seq=5 ttl=114 time=44.8 ms
[1649762005.529398] 64 bytes from 8.8.8.8: icmp_seq=6 ttl=114 time=45.0 ms
[1649762006.539454] 64 bytes from 8.8.4.4: icmp_seq=6 ttl=114 time=52.7 ms
[1649762007.529282] 64 bytes from 8.8.8.8: icmp_seq=7 ttl=114 time=42.6 ms
[1649762008.539210] 64 bytes from 8.8.4.4: icmp_seq=7 ttl=114 time=49.5 ms
[1649762009.539393] 64 bytes from 8.8.8.8: icmp_seq=8 ttl=114 time=49.8 ms
[1649762010.538313] 64 bytes from 8.8.4.4: icmp_seq=8 ttl=114 time=45.9 ms
[1649762011.541687] 64 bytes from 8.8.8.8: icmp_seq=9 ttl=114 time=50.0 ms
[2]+  Stopped (signal)           ping -D -v -n -i 2 8.8.4.4
[1]-  Stopped (signal)           ping -D -v -n -i 2 8.8.8.8
root@OpenWrt:~# [1649762017.559402] 64 bytes from 8.8.4.4: icmp_seq=9 ttl=114 time=53.2 ms
[1649762018.559398] 64 bytes from 8.8.8.8: icmp_seq=10 ttl=114 time=52.8 ms
[1649762019.556848] 64 bytes from 8.8.4.4: icmp_seq=10 ttl=114 time=48.2 ms
[1649762020.557457] 64 bytes from 8.8.8.8: icmp_seq=11 ttl=114 time=48.8 ms
[1649762021.557382] 64 bytes from 8.8.4.4: icmp_seq=11 ttl=114 time=47.4 ms
[1649762022.560341] 64 bytes from 8.8.8.8: icmp_seq=12 ttl=114 time=50.3 ms
[1649762023.559345] 64 bytes from 8.8.4.4: icmp_seq=12 ttl=114 time=46.7 ms
[1649762024.559441] 64 bytes from 8.8.8.8: icmp_seq=13 ttl=114 time=46.8 ms
[1649762025.558389] 64 bytes from 8.8.4.4: icmp_seq=13 ttl=114 time=43.9 ms
```

**Comment by moeller0** [comment]
> The latter option is perhaps simpler?

That will probably also kill the old baseline state, no? So after the ping sleep things will start with having to learn a new baseline. Which after a long sleep, might actually be the right thing to do anyway, no?

**Comment by lynxthecat** [comment]
Crap didn't think about that. If I wait to obtain the baseline updates as well that will mean introducing a little delay. But during this time the bandwidth will remain set to minimum so perhaps that is OK?

**Comment by moeller0** [comment]
So what I would do instead is in the monitor_reflector scripts/function:
1) add a variable reflector_is_working=0
2) add a counter for consecutive good and bad samples (judged by a timeout criterion most likely)
         sample_counter
3)
```
 if [  "${reflector_is_working}" -eq "0"  -a  "${sample_counter}" -gt "10" ] ;
then
         # actually write data to the FIFO,
fi
```
4) 
```
if [  "${reflector_is_working}" -eq "0"  -a  "${sample_counter}" -lt "-10" ] ;
then
        reflector_is_working=1
         # actually write data to the FIFO that signal the reflector is bad and should be replaced, potentially via a negative $sample_counter
fi
```

If a reflector is flapping between <10 good and bad samples it should be rejected as well, so maybe add a timeout if after 20 intervals reflector_is_working is still 0, or similar.


This is just shellish pseudo code that is probably broken... ;) but you get the idea, do not put that into the main script but simply do not

**Comment by moeller0** [comment]
> How many responses / over what period do we need for decent baseline?

The more the better, but if we are sure about the link not being permanently congested even a single sample is fine, as the code updates the baseline on every sample with a strong bias towards smaller samples, so the should converge on the true baseline quickly, as long as we do not restart under massive prolonged congestion. But I think the ping wakeup happens at a really lowish achieved throughput so there is little risk of the problematic situation happening. And since this is a heuristic it might be "good enough" already...

**Comment by lynxthecat** [comment]
I really like your proposal above. Very elegant. 

What should the counter max out to? 20?

**Comment by moeller0** [comment]
> What should the counter max out at? 20?

The counter, IMHO should really count consecutive good or bad samples (by whichever criterion) with resetting to zero when switching between good and bad or bad and good. There is no real need to max it out, as long as we avoid wrap-around where positive numbers become negative, but there is also limited value in keeping large counts here... so for the implementation maybe ceil the counter at 10*60*60*24 = 864000 the maximal number of 10Hz samples in a day?

**Comment by lynxthecat** [comment]
But I thought the idea is that we increment the counter on good sample, and decrement on bad, and if a sufficient number of bad, then the reflector is silenced until it becomes good by 10 good samples again. If we allow the counter to go up really high, e.g. to 10,000 or more then doesn't that mean we will need at least 10,000 bad samples to classify reflector as bad?

**Comment by moeller0** [comment]
> > But I thought the idea is that we increment the counter on good sample, and decrement on bad, and if a sufficient number of bad, then the reflector is silenced until it becomes good by 10 good samples again. If we allow the counter to go up really high, e.g. to 10,000 or more then doesn't that mean we will need at least 10,000 bad samples to classify reflector as bad?
> 
> Not sure that will work:
> 
> 1. as in your text: 1000 good samples followed by 100 bad samples will still be massively positive, but a reflector producing no valid sample in ~10 seconds surely should be jettisoned?
> 2. or think a flapping reflector giving 1 good for each bad sample, which will simply switch between two values X and X-1 and hence not look suspicious while the reflector is bad 50% of the time...
> 
> All of this can be fixed with more complexity, but the question is, is that actually worth it?
> 
> I think the rest to zero on switches (good<->bad) solves at least 1) above and in your text... which might be good enough? And for 2) this is going to be rare, hopefully rare enough to simply ignore it... (the obvious fix is to keep independent counters for the last X samples giving the count of good and bad samples each, which allows to calculate the ratio as well, but let's not overcomplicate things before it seems needed....)

Technically, instead of the reset to zero method, a ceiled addition as you propose will mostly end up solving the same issue as well, and since introducing a ceiling/floor seems prudent that might be the best way forward. So I think your design is superior, put the ceiling at 10, declare a reflector good/up when it hits a score of 10 and take it out of service when it hits -10... (and signal the -10 score to the main loop so that a new reflector IP can be picked and started).

**Comment by lynxthecat** [comment]
Good. And can't we just leave ping process in background on -10 incase the ping process manages to recover and get back to +10? This would deal with temporary reflector downtime.

**Comment by moeller0** [comment]
In the case of a -10 there have been 20 consecutive bad samples from that reflector already... 
On any bad sample you either do not send the result to the main loop at all, or with a field denoting invalid sample (say a negative rtt, and obviously the current badness count) then  the main loop can decide when to replace a reflector... or when to ignore that.

**Comment by lynxthecat** [comment]
I haven't implemented the correction aspect yet. We can timeout based on the variable shaper rate influenced data inside main loop (because that's available there, and I am not sure we should implement flock + read inside each reflector loop for this). However with setting -O inside main loop I can just pick up on the no response output of iputils-ping (it issues no response messages if no response before the next send)?

Otherwise @patrakov the ping sync issue you raised should be fixed with this commit:

https://github.com/lynxthecat/CAKE-autorate/commit/ad95c164a0a447513d238bf48e9fcf51b9d06ac8

**Comment by patrakov** [comment]
Synchronization still happens after radio hiccups. Please reopen.

Note that the version is patched for the following things unrelated to this bug:

* The first column is added as a human-readable timestamp
* Ping is instructed to use a particular interface and firewall mark, for compatibility with mwan3 (which is configured to send the laptop's traffic over LTE instead of fiber, for debugging)
* Bufferbloat on an idle connection is ignored, except for resetting the timestamp and printing a DEBUG line

The patch and the settings: 
[cake-autorate.diff.txt](https://github.com/lynxthecat/cake-autorate/files/9550560/cake-autorate.diff.txt)

The logs, gzipped: 
[cake-autorate.log.gz](https://github.com/lynxthecat/cake-autorate/files/9550595/cake-autorate.log.gz)

**Comment by patrakov** [comment]
I think we have no choice except to limit the number of pings for each reflector, and realign the timestamp to the "correct" one after each batch.

**Comment by lynxthecat** [comment]
I have been working through your changes and have implemented at least the ping options and also the timestamp for output lines when writing to a file. Will commit shortly.

**Comment by lynxthecat** [comment]
Can you please explain the cause of the synchronization issue at your end? Optional global timeout could also work.

**Comment by patrakov** [comment]
I don't know why for sure the pings become synchronized. What I can surely say is that the sleep function is not the cause, because it is disabled. The log is there, you can see how it developed.

**Comment by lynxthecat** [comment]
fping is an alternative round robin ping program. It is probably better at keeping timing right. I don't suffer from this ping synchronization issue you have though. I think earlier we established that if you have 2x ping processes running and pause them, then restart them, they become synchronized. That's weird. 

Are you running an odd/old OpenWrt setup I wonder?

**Comment by patrakov** [comment]
This is an OpenWRT 22.03.0 on Linksys E8450.

**Comment by lynxthecat** [comment]
Same here. Aren't your pings pretty good at keeping time? See e.g. output of:

`ping -i 0.1 -D 1.1.1.1 | while read x _; do x=${x//[[\[\].]}; echo $(($x-$y)); y=$x; done`

**Comment by patrakov** [comment]
I think it might be due to stalls. Not checked, but it seems to be the only relevant difference between our links.

**Comment by patrakov** [comment]
It is due to stalls and lost packets. Demo (on fiber):

```
# ping -D -v -c 20 -n -i 2 8.8.8.8 & sleep 1 ; ping -D -v -c 20 -n -i 2 8.8.4.4 & sleep 10 ; iptables -I INPUT 1 -s 8.8.8.8 -j DROP & sleep 13 ; iptables -D INPUT -s 8.8.8.8 -j DROP & wait
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
[1663460701.841128] 64 bytes from 8.8.8.8: icmp_seq=1 ttl=116 time=34.0 ms
PING 8.8.4.4 (8.8.4.4) 56(84) bytes of data.
[1663460702.843441] 64 bytes from 8.8.4.4: icmp_seq=1 ttl=117 time=32.6 ms
[1663460703.840450] 64 bytes from 8.8.8.8: icmp_seq=2 ttl=116 time=31.9 ms
[1663460704.845744] 64 bytes from 8.8.4.4: icmp_seq=2 ttl=117 time=32.7 ms
[1663460705.842448] 64 bytes from 8.8.8.8: icmp_seq=3 ttl=116 time=31.8 ms
[1663460706.847749] 64 bytes from 8.8.4.4: icmp_seq=3 ttl=117 time=32.5 ms
[1663460707.844842] 64 bytes from 8.8.8.8: icmp_seq=4 ttl=116 time=32.2 ms
[1663460708.850370] 64 bytes from 8.8.4.4: icmp_seq=4 ttl=117 time=32.4 ms
[1663460709.847354] 64 bytes from 8.8.8.8: icmp_seq=5 ttl=116 time=32.3 ms
[1663460710.853385] 64 bytes from 8.8.4.4: icmp_seq=5 ttl=117 time=32.8 ms
[1663460711.855689] 64 bytes from 8.8.8.8: icmp_seq=6 ttl=116 time=38.1 ms
[1663460712.855389] 64 bytes from 8.8.4.4: icmp_seq=6 ttl=117 time=32.8 ms
[1663460714.857406] 64 bytes from 8.8.4.4: icmp_seq=7 ttl=117 time=32.8 ms
[1663460716.859393] 64 bytes from 8.8.4.4: icmp_seq=8 ttl=117 time=32.8 ms
[1663460718.862409] 64 bytes from 8.8.4.4: icmp_seq=9 ttl=117 time=32.8 ms
[1663460720.864670] 64 bytes from 8.8.4.4: icmp_seq=10 ttl=117 time=33.1 ms
[1663460722.866628] 64 bytes from 8.8.4.4: icmp_seq=11 ttl=117 time=32.8 ms
[1663460724.868186] 64 bytes from 8.8.4.4: icmp_seq=12 ttl=117 time=32.9 ms
[1663460726.297547] 64 bytes from 8.8.8.8: icmp_seq=13 ttl=116 time=32.3 ms
[1663460726.870167] 64 bytes from 8.8.4.4: icmp_seq=13 ttl=117 time=32.8 ms
[1663460728.299795] 64 bytes from 8.8.8.8: icmp_seq=14 ttl=116 time=32.1 ms
[1663460728.873221] 64 bytes from 8.8.4.4: icmp_seq=14 ttl=117 time=32.9 ms
[1663460730.302054] 64 bytes from 8.8.8.8: icmp_seq=15 ttl=116 time=32.1 ms
[1663460730.875229] 64 bytes from 8.8.4.4: icmp_seq=15 ttl=117 time=32.8 ms
[1663460732.304588] 64 bytes from 8.8.8.8: icmp_seq=16 ttl=116 time=32.4 ms
[1663460732.877219] 64 bytes from 8.8.4.4: icmp_seq=16 ttl=117 time=32.8 ms
[1663460734.307086] 64 bytes from 8.8.8.8: icmp_seq=17 ttl=116 time=32.3 ms
[1663460734.880215] 64 bytes from 8.8.4.4: icmp_seq=17 ttl=117 time=32.8 ms
[1663460736.309092] 64 bytes from 8.8.8.8: icmp_seq=18 ttl=116 time=31.8 ms
[1663460736.883235] 64 bytes from 8.8.4.4: icmp_seq=18 ttl=117 time=32.8 ms
[1663460738.311624] 64 bytes from 8.8.8.8: icmp_seq=19 ttl=116 time=32.4 ms
[1663460738.885497] 64 bytes from 8.8.4.4: icmp_seq=19 ttl=117 time=33.1 ms
[1663460740.314094] 64 bytes from 8.8.8.8: icmp_seq=20 ttl=116 time=32.3 ms
[1663460740.887511] 64 bytes from 8.8.4.4: icmp_seq=20 ttl=117 time=32.8 ms

--- 8.8.4.4 ping statistics ---
20 packets transmitted, 20 received, 0% packet loss, time 38044ms
rtt min/avg/max/mdev = 32.445/32.796/33.081/0.153 ms

--- 8.8.8.8 ping statistics ---
20 packets transmitted, 14 received, 30% packet loss, time 38474ms
rtt min/avg/max/mdev = 31.827/32.719/38.144/1.586 ms
[4]+  Done                       iptables -D INPUT -s 8.8.8.8 -j DROP
[3]+  Done                       iptables -I INPUT 1 -s 8.8.8.8 -j DROP
[2]+  Done                       ping -D -v -c 20 -n -i 2 8.8.4.4
[1]+  Done                       ping -D -v -c 20 -n -i 2 8.8.8.8
```

**Comment by lynxthecat** [comment]
@moeller0 do you understand the above?

**Comment by moeller0** [comment]
I believe that we might run into an issue of scope. We ideally want equidistant sampling (that is echo requests sent out on a reliably clock), but that is not really what most ping users might be after... one solution would be to stop and start pingers after a resolved stall with the desired offset.

**Comment by moeller0** [comment]
Note how initially 8.8.8.8 is on odd seconds and later on even seconds, while 8.8.4.4 was on even abd stays on even seconds.

**Comment by patrakov** [comment]
What I did for the test was to set up a pair of interleaved pingers, one to 8.8.8.8 and another to 8.8.4.4, and then disrupt communication with 8.8.8.8 for a few seconds.

Regarding the suggestion to "stop and start pingers after a resolved stall with the desired offset", I would say that my definition of "stall" doesn't work for this purpose, because it does not include the situation where only pings are stalled while other traffic flows. If there is anything that we should detect, it is the effect (synchronization), not the presumed cause (stall).

**Comment by moeller0** [comment]
Well detection is hard. How about simply restartingvpingers after, say 10000 to 11000 pings and restart them with the correct offset?

**Comment by patrakov** [comment]
This would also work, and that's what I suggested before, see https://github.com/lynxthecat/cake-autorate/issues/24#issuecomment-1244105367 (but note that 10000 to 11000 pings would be too much for the reduced ping rate that I use, maybe we should base it on the total time, something like 5 minutes, not the number of pings).

**Comment by moeller0** [comment]
Just saw your comment after editing mine, so yes, time based seems better.

**Comment by moeller0** [comment]
I guess the only thing to try would be not to do this with all pingers at the same time...

**Comment by lynxthecat** [comment]
@patrakov what would you think about switching over to fping? That would resolve this issue entirely I think since it sends out pings round robin with a set interval between sends.

**Comment by patrakov** [comment]
Go for it, if it works.

**Comment by lynxthecat** [comment]
Any thoughts on that @moeller0? 

@patrakov does it work with your funky mwan3 stuff?

**Comment by patrakov** [comment]
Regarding mwan3 + fping, it doesn't have the option to set the firewall mark. However, mwan3 contails a preloadable library that fixes this gap:

```
root@OpenWrt:~# LD_PRELOAD=/lib/mwan3/libwrap_mwan3_sockopt.so.1.0 INTERFACE=wwan0 FWMARK=$(( 0x300 )) fping -l --timestamp -i 500 1.0.0.1 1.1.1.1
[1663510889.43266] 1.0.0.1 : [0], 64 bytes, 78.9 ms (78.9 avg, 0% loss)
[1663510889.91167] 1.1.1.1 : [0], 64 bytes, 57.5 ms (57.5 avg, 0% loss)
[1663510890.41168] 1.0.0.1 : [1], 64 bytes, 57.0 ms (68.0 avg, 0% loss)
[1663510890.93269] 1.1.1.1 : [1], 64 bytes, 77.5 ms (67.5 avg, 0% loss)
[1663510891.41168] 1.0.0.1 : [2], 64 bytes, 56.1 ms (64.0 avg, 0% loss)
[1663510891.94369] 1.1.1.1 : [2], 64 bytes, 87.6 ms (74.2 avg, 0% loss)
[1663510892.41068] 1.0.0.1 : [3], 64 bytes, 54.1 ms (61.5 avg, 0% loss)
[1663510892.93167] 1.1.1.1 : [3], 64 bytes, 74.7 ms (74.3 avg, 0% loss)
[1663510893.41467] 1.0.0.1 : [4], 64 bytes, 57.2 ms (60.7 avg, 0% loss)
[1663510893.93269] 1.1.1.1 : [4], 64 bytes, 74.7 ms (74.4 avg, 0% loss)
[1663510894.41371] 1.0.0.1 : [5], 64 bytes, 55.3 ms (59.8 avg, 0% loss)
[1663510894.94065] 1.1.1.1 : [5], 64 bytes, 82.2 ms (75.7 avg, 0% loss)
[1663510895.41568] 1.0.0.1 : [6], 64 bytes, 56.7 ms (59.3 avg, 0% loss)
[1663510895.93367] 1.1.1.1 : [6], 64 bytes, 74.3 ms (75.5 avg, 0% loss)
^C
1.0.0.1 : xmt/rcv/%loss = 7/7/0%, min/avg/max = 54.1/59.3/78.9
1.1.1.1 : xmt/rcv/%loss = 7/7/0%, min/avg/max = 57.5/75.5/87.6
```

**Comment by lynxthecat** [comment]
So thumbs up for fping?

**Comment by patrakov** [comment]
Yes.

**Comment by moeller0** [comment]
I would not opt for switching to fping. ip-utils ping is likely to stay available for OpenWrt for the forseeable future, fping less so. So fping as an option yea; fping as only option nay... not that I have anything more than an opinion.

**Comment by lynxthecat** [comment]
@patrakov if you issue 'kill -STOP' and 'kill -CONT' to ping does that start off timer afresh? So could we use those to periodically readjust the timings?

**Comment by patrakov** [comment]
For me, "fping vs limiting the number of pings" does not matter, because both solutions are likely to work. And both are temporary because of OWD, for which we would need some new tool (likely custom), therefore the issue of possible non-longevity of fping does not matter.

Regarding `kill -STOP` / `kill -CONT`, yes it happens to adjust the timestamp and break synchronization, but this behavior is not documented and therefore should not be relied upon. Limiting the number of pings and readjusting the next batch start time is guaranteed to work.

**Comment by lynxthecat** [comment]
How about every ping health check interval I calculate average separation between the ping responses and if they deviate sufficiently then do a timing refresh? @moeller0 what do you think? If this could work would you be able to suggest such a separation test/metric to use to ensure the responses are nice and even?

**Comment by patrakov** [comment]
That would be tricky, because you need to figure out the cause of the deviation. It might be due to a momentary bufferbloat that get one ping delayed by exactly the interval, and this would self-correct. Or it could be this persistent synchronization issue that I still don't fully understand.

**Comment by lynxthecat** [comment]
Yes I know but I think there could still be a way. If taken over a reasonable length of time the average would deal with this.

**Comment by moeller0** [comment]
> For me, "fping vs limiting the number of pings" does not matter, because both solutions are likely to work. And both are temporary because of OWD, for which we would need some new tool (likely custom), therefore the issue of possible non-longevity of fping does not matter.

Not sure I agree, OWDs are not and unfortunately will not be as ubiquitous as ICMP RTTs, so making sure cake-autorate continues to work well with RTTs seems a good idea.



> How about every ping health check interval we calculate average separation between the ping responses and if they deviate sufficiently then do a timing refresh? @moeller0 what do you think? If this could work would you be able to suggest such a separation test/metric to use to ensure the responses are nice and even?

Sounds tricky, I would simply do this on a fixed interval and just accept any synchronization happening in between.
The point is, ping times will never be super precise so we have o accept some slack and if we then have tighter expected distances between pings than @patrakov's 1 second (from the test) it gets really hard to decide how much "deviation" from ideal starting times we are willing to accept... especially if inter ping intervals start to become smallish.

> Is there no way to have bash itself control timing of pings e.g. with netcat or some other means? Could we actually just use -STOP and -CONT to send one ping out at the exact millisecond we want?

Restarting the ping process, has the additional advantage that the log file we write to `/tmp` will not grow forever, or is this already controlled in any other way?

**Comment by moeller0** [comment]
If you must, you could check for lost pings and only re-start if some pings were lost. But honestly, why bother just restart often enough to not bother, but not so often that potential restart delays hurt.

**Comment by lynxthecat** [comment]
Yeah there are issues with OWDs it seems. And I see your point about iputils-ping vs fping. 

What sort of default time period should we restart/redistribute timings of the pings? Does every 10 ping reflector health check loops seems reasonable? Any thoughts on that @patrakov?

**Comment by patrakov** [comment]
No idea.

**Comment by moeller0** [comment]
> What sort of default time period should we restart/redistribute timings of the pings? Does every 10 ping reflector health check loops seems reasonable? Any thoughts on that @patrakov?

Reaching into my trusty store of thin/hot air, I would say below 10 seconds sounds way to often, and above 10 minutes to much, so without much consideration, why not aim for say 1 minute +/-, so if "10 ping reflector health check loops" gets us into that range that sounds fine.

**Comment by lynxthecat** [comment]
I got frustrated with messing about with starting and stopping multiple ping instances and just wrote a new branch that uses fping:

https://github.com/lynxthecat/cake-autorate/tree/stall-detection-fping

@patrakov it probably has a glitch or two needing ironing out, but maybe you could try testing this?

**Comment by patrakov** [comment]
So far here are the results:

1. This line is a bit too fragile:

```
		[[ $timeout -eq "timed" ]] && continue
```

While playing with extra fping arguments, I got "bytes," (yes, with the trailing comma) in $timeout, which resulted in a syntax error. Anyway `-eq` is supposed to be an arithmetic comparison operator, and here we are dealing with strings. Normally in this place we have the number of bytes in the packet. So maybe have something like this instead, to catch more error cases?

```
		[[ $timeout =~ ^[0-9]+$ ]] || continue
```

2. I could not get satisfactory results through `fping` arguments, so I had to modify the command line in the init script as follows:

```
        procd_set_param command mwan3 use lte /root/cake-autorate/cake-autorate.sh
```

Other than that, it seems to work. But also, the LTE connection right now is much better than usual, let's wait until 9PM to see how it degrades.

**Comment by lynxthecat** [comment]
Sounds good. Yes that line was cribbed from before I learnt about bash. I am going to have a hard look at all the matches and will carefully consider your suggestion.

**Comment by moeller0** [comment]
> I got frustrated with messing about with starting and stopping multiple ping instances and just wrote a new branch that uses fping:

My biggest question is, what does the current version do anyway, does it continuously log into a file in `/tmp` that ultimately might grow too large (causing filesystem full or OOM errors) or not. If these files are growing continuously then restarting the ping processes (not the pingers, but the call to the ping binary inside pinger) after X samples seems like a required feature to add anyway, especially considering routers with little storage and little RAM.

The logic is not all that hard, use `-c X` to have ping finish eventually and sent the initial start time (offset) and intra-ping interval store that, than on restart simply calculate the next start time:
$(( (($now - $offset) % $interval) + $now ))
and make sure the next ping is started roughly at the right time by using an appropriate sleep call.

**Comment by lynxthecat** [comment]
fping writes out to a Linux pipe (fifo), which the main loop then reads from. I think the pipe max size is 64kbytes and will block on max size hit. Perhaps I should test that!

**Comment by moeller0** [comment]
How about ip-utuls ping, where does this write to?
I am happy if that is fixed already! This is just a predictable future issue, so we might as well make sure this is fixed, and add a comment to the code about that effect.

**Comment by lynxthecat** [comment]
With iputils-ping each ping instance writes to its own fifo and then there is a corresponding monitor reflector instance that reads in from those fifos and outputs to a global fifo that is read in by the main loop. So again I *think* that's covered owing to use of fifos. 

One big issue is the log file - that can grow to memory capacity. Any thoughts on how to handle that? We could check file size periodically and exit script unless override is set. Or something else more clever perhaps?

**Comment by moeller0** [comment]
> With iputils-ping each ping instance writes to its own fifo and then there is a corresponding monitor reflector instance that reads in from those fifos and outputs to a global fifo that is read in by the main loop. So again I _think_ that's covered owing to use of fifos.

Excellent! I was under the illusion that ping would still write a real logfile...



> One big issue is the log file - that can grow to memory capacity. Any thoughts on how to handle that? We could check file size periodically and exit script unless override is set. Or something else more clever perhaps?

I would do something like cycle between two logfiles every X hours (default 24) and always keep the las complete and the currently written one, once the time is up again, delete the last complete one, move the current one to the lasst complete one and start again. That way there is never more than 2X hours worth of logfile. People who want longer term logs simply set a huuuuge X everybody else just sets X to allow some meaningful debugging. In the config file just note the large Xs can easi;ly cause OOM and users need to be careful.

The whole scheme allows for fancier techniques, like compressing the last completed log file, or keeping multiple generations, but IMHO just having something like the above even with X set to one hour probably would work well enough in practice to capture relevant logging data while likely avoiding causing harm...

**Comment by lynxthecat** [comment]
OK I will implement that - @patrakov any thoughts/comments on the suggestion above?

**Comment by moeller0** [comment]
Oh, maybe start each log file with dumping the names of the columns into the file (unless that is done already)?
That way CSV importers in Excel can automatically detect the column names making handling the data simpler.

**Comment by lynxthecat** [comment]
Do you think there should be separate files for DEBUG and DATA?

**Comment by moeller0** [comment]
Good idea, yes, that will make parsing them simpler (as all lines in the data file will be of identical format).
However for console output it might be nice to interleave them.
If you end up interleaving them also in one log file, please put a record type identifier into the first column, like:
HEADER, DATA, DEBUG
so any fancy parser can detect the record type of a line quickly and unambiguously...
also fro my experience with writing shitty parsers for shitty log files, it helps to use unambiguous and easily visible column separators. My preference is to use `;` (semi-colon) as comata are used in German as decimal separator, so `'` and `.` are clearly off-limits and `:` can be useful as say internal separator in DEBUG records.

**Comment by moeller0** [comment]
Looks good.
However maybe consider:
1) moving the RECORDTYPE field to first position and the timestamp to second and add LOGGINGTIMESTAMP to the header:

HEADER LOGGINGTIMESTAMP PROC_TIME_US DL_ACHIEVED_RATE_KBPS UL_ACHIEVED_RATE_KBPS DL_LOAD_PERCENT UL_LOAD_PERCEN RTT_TIMESTAMP REFLECTOR SEQUENCE RTT_BASELINE RTT_US RTT_DELTA_US ADJ_DELAY_THR SUM_DELAYS DL_LOAD_CONDITION UL_LOAD_CONDITION CAKE_DL_RATE_KBPS CAKE_UL_RATE_KBPS
so the header line only contains the names of data columns and no timestamp itself? (who cares at what time we logged this line out to the log file).

2) I would not add a specific column header for RECORDTYPE, excel will not mind naming the column header, and any other parser can use this information available at the start of each line to select the correct parsing function.

3) maybe really add ";" as columns separators to make CSV import better defined.

**Comment by lynxthecat** [comment]
```
root@OpenWrt:~/cake-autorate# ./cake-autorate.sh
DEBUG;2022-09-20-10:04:28_1663664668.944716;Starting CAKE-autorate 1.0.0
DEBUG;2022-09-20-10:04:28_1663664668.945589;Down interface: ifb-dl (10000 / 25000 / 80000)
DEBUG;2022-09-20-10:04:28_1663664668.946367;Up interface: ifb-ul (25000 / 30000 / 35000)
DEBUG;2022-09-20-10:04:28_1663664668.947212;rx_bytes_path: /sys/class/net/ifb-dl/statistics/tx_bytes
DEBUG;2022-09-20-10:04:28_1663664668.948204;tx_bytes_path: /sys/class/net/ifb-ul/statistics/rx_bytes
HEADER;LOG_TIME;PROC_TIME_US;DL_ACHIEVED_RATE_KBPS;UL_ACHIEVED_RATE_KBPS;DL_LOAD_PERCENT;UL_LOAD_PERCENT;RTT_TIMESTAMP;REFLECTOR;SEQUENCE;RTT_BASELINE;RTT_US;RTT_DELTA_US;ADJ_DELAY_THR;SUM_DELAYS;DL_LOAD_CONDITION;UL_LOAD_CONDITION;CAKE_DL_RATE_KBPS;CAKE_UL_RATE_KBPS
DATA;2022-09-20-10:04:29_1663664669.053601;1663664669.053277;0;0;0;0;1663664669.04806;1.1.1.1;0;143650;48500;-951500;25933;0;dl_idle;ul_idle;25000;30000
DATA;2022-09-20-10:04:29_1663664669.105248;1663664669.104820;0;0;0;0;1663664669.09902;1.0.0.1;0;141400;46000;-954000;25933;0;dl_idle;ul_idle;25000;30000
DATA;2022-09-20-10:04:29_1663664669.151385;1663664669.150965;0;0;0;0;1663664669.14491;8.8.8.8;0;137620;41800;-958200;25933;0;dl_idle;ul_idle;25000;30000
DATA;2022-09-20-10:04:29_1663664669.203248;1663664669.202686;594;1810;2;6;1663664669.19495;8.8.4.4;0;137530;41700;-958300;25933;0;dl_low;ul_low;25000;30000
DATA;2022-09-20-10:04:29_1663664669.248157;1663664669.247791;594;1810;2;6;1663664669.24186;1.1.1.1;1;49015;38500;-105150;25933;0;dl_low;ul_low;25000;30000
DATA;2022-09-20-10:04:29_1663664669.317658;1663664669.316906;594;1810;2;6;1663664669.30656;1.0.0.1;1;61930;53100;-88300;25933;0;dl_low;ul_low;25000;30000
DATA;2022-09-20-10:04:29_1663664669.351571;1663664669.351146;594;1810;2;6;1663664669.34701;8.8.8.8;1;52822;43400;-94220;25933;0;dl_low;ul_low;25000;30000
DATA;2022-09-20-10:04:29_1663664669.402585;1663664669.401783;704;1791;2;5;1663664669.39703;8.8.4.4;1;52723;43300;-94230;25933;0;dl_low;ul_low;25000;30000
DATA;2022-09-20-10:04:29_1663664669.448116;1663664669.447664;704;1791;2;5;1663664669.44186;1.1.1.1;2;39101;38000;-11015;25933;0;dl_low;ul_low;25000;30000
DATA;2022-09-20-10:04:29_1663664669.515179;1663664669.514430;704;1791;2;5;1663664669.50496;1.0.0.1;2;52093;51000;-10930;25933;0;dl_low;ul_low;25000;30000
DATA;2022-09-20-10:04:29_1663664669.550064;1663664669.549651;704;1791;2;5;1663664669.54389;8.8.8.8;2;40922;39600;-13222;25933;0;dl_low;ul_low;25000;30000
DATA;2022-09-20-10:04:29_1663664669.605285;1663664669.604485;577;1751;2;5;1663664669.59499;8.8.4.4;2;41812;40600;-12123;25933;0;dl_low;ul_low;25000;30000
DATA;2022-09-20-10:04:29_1663664669.656120;1663664669.655584;577;1751;2;5;1663664669.65136;1.1.1.1;3;39108;46900;7799;25933;0;dl_low;ul_low;25000;30000
DATA;2022-09-20-10:04:29_1663664669.704116;1663664669.703849;577;1751;2;5;1663664669.69602;1.0.0.1;3;42199;41100;-10993;25933;0;dl_low;ul_low;25000;30000
DATA;2022-09-20-10:04:29_1663664669.748028;1663664669.747680;577;1751;2;5;1663664669.74292;8.8.8.8;3;38202;37900;-3022;25933;0;dl_low;ul_low;25000;30000
DATA;2022-09-20-10:04:29_1663664669.804515;1663664669.804237;663;1536;2;5;1663664669.79402;8.8.4.4;3;38831;38500;-3312;25933;0;dl_low;ul_low;25000;30000
DATA;2022-09-20-10:04:29_1663664669.850882;1663664669.850554;663;1536;2;5;1663664669.84595;1.1.1.1;4;39108;39200;92;25933;0;dl_low;ul_low;25000;30000
^CINFO;2022-09-20-10:04:29_1663664669.902477;
INFO;2022-09-20-10:04:29_1663664669.903750;Killing all background processes and cleaning up /tmp files.
```

![image](https://user-images.githubusercontent.com/10721999/191217656-c41bf4f1-a75f-4c84-b2ed-0fdcba40beea.png)

**Comment by moeller0** [comment]
Excellent, looks good.
If you want you can still pad inside each column with spaces for making things more readable on the console
and maybe split LOG_TIME/2022-09-20-10:04:29_1663664669.605285 into 
LOG_DATETIME/2022-09-20-10:04:29 and LOG TIMESTAMP/1663664669.605285 (this should make consuming these two by a parser simpler), but that is a matter of personal taste, if you like the current version better stick to it!

**Comment by lynxthecat** [comment]
```
root@OpenWrt:~/cake-autorate# ./cake-autorate.sh
DEBUG; 2022-09-20-10:42:59; 1663666979.225890; Starting CAKE-autorate 1.0.0
DEBUG; 2022-09-20-10:42:59; 1663666979.226917; Down interface: ifb-dl (10000 / 25000 / 80000)
DEBUG; 2022-09-20-10:42:59; 1663666979.227741; Up interface: ifb-ul (25000 / 30000 / 35000)
DEBUG; 2022-09-20-10:42:59; 1663666979.228226; rx_bytes_path: /sys/class/net/ifb-dl/statistics/tx_bytes
DEBUG; 2022-09-20-10:42:59; 1663666979.228702; tx_bytes_path: /sys/class/net/ifb-ul/statistics/rx_bytes
HEADER; LOG_DATETIME; LOG_TIMESTAMP; PROC_TIME_US; DL_ACHIEVED_RATE_KBPS; UL_ACHIEVED_RATE_KBPS; DL_LOAD_PERCENT; UL_LOAD_PERCENT; RTT_TIMESTAMP; REFLECTOR; SEQUENCE; RTT_BASELINE; RTT_US; RTT_DELTA_US; ADJ_DELAY_THR; SUM_DELAYS; DL_LOAD_CONDITION; UL_LOAD_CONDITION; CAKE_DL_RATE_KBPS; CAKE_UL_RATE_KBPS
DATA; 2022-09-20-10:42:59; 1663666979.332449; 1663666979.332025;0;0;0;0;1663666979.32591;1.1.1.1;0;138880;43200;-956800;25933;0;dl_idle;ul_idle;25000;30000
DATA; 2022-09-20-10:42:59; 1663666979.379959; 1663666979.379701;0;0;0;0;1663666979.37491;1.0.0.1;0;137260;41400;-958600;25933;0;dl_idle;ul_idle;25000;30000
DATA; 2022-09-20-10:42:59; 1663666979.429643; 1663666979.429382;0;0;0;0;1663666979.42105;8.8.8.8;0;133300;37000;-963000;25933;0;dl_idle;ul_idle;25000;30000
DATA; 2022-09-20-10:42:59; 1663666979.489028; 1663666979.488593;571;1569;2;5;1663666979.47922;8.8.4.4;0;140500;45000;-955000;25933;0;dl_low;ul_low;25000;30000
DATA; 2022-09-20-10:42:59; 1663666979.531333; 1663666979.530763;571;1569;2;5;1663666979.52103;1.1.1.1;1;46468;36200;-102680;25933;0;dl_low;ul_low;25000;30000
DATA; 2022-09-20-10:42:59; 1663666979.595302; 1663666979.594746;571;1569;2;5;1663666979.58618;1.0.0.1;1;59266;50600;-86660;25933;0;dl_low;ul_low;25000;30000
DATA; 2022-09-20-10:42:59; 1663666979.639723; 1663666979.638956;571;1569;2;5;1663666979.62806;8.8.8.8;1;51310;42200;-91100;25933;0;dl_low;ul_low;25000;30000
DATA; 2022-09-20-10:42:59; 1663666979.683932; 1663666979.683671;745;1850;2;6;1663666979.67995;8.8.4.4;1;53560;43900;-96600;25933;0;dl_low;ul_low;25000;30000
DATA; 2022-09-20-10:42:59; 1663666979.741093; 1663666979.739721;745;1850;2;6;1663666979.72705;1.1.1.1;2;41456;40900;-5568;25933;0;dl_low;ul_low;25000;30000
DATA; 2022-09-20-10:42:59; 1663666979.782255; 1663666979.781966;745;1850;2;6;1663666979.77493;1.0.0.1;2;40756;38700;-20566;25933;0;dl_low;ul_low;25000;30000
DATA; 2022-09-20-10:42:59; 1663666979.836639; 1663666979.835596;745;1850;2;6;1663666979.82203;8.8.8.8;2;37261;35700;-15610;25933;0;dl_low;ul_low;25000;30000
DATA; 2022-09-20-10:42:59; 1663666979.889454; 1663666979.889193;718;1526;2;5;1663666979.88403;8.8.4.4;2;48106;47500;-6060;25933;0;dl_low;ul_low;25000;30000
DATA; 2022-09-20-10:42:59; 1663666979.931375; 1663666979.931114;718;1526;2;5;1663666979.92476;1.1.1.1;3;38435;38100;-3356;25933;0;dl_low;ul_low;25000;30000
DATA; 2022-09-20-10:42:59; 1663666979.979674; 1663666979.979411;718;1526;2;5;1663666979.97405;1.0.0.1;3;37645;37300;-3456;25933;0;dl_low;ul_low;25000;30000
^CINFO; 2022-09-20-10:43:00; 1663666980.006088;
INFO; 2022-09-20-10:43:00; 1663666980.007318; Killing all background processes and cleaning up /tmp files.
```

**Comment by moeller0** [comment]
DL_LOAD_PERCENT: maybe shorten to PCT?
RTT_TIMESTAMP: maybe add _SEC?
RTT_BASELINE: maybe add unit _MS? 
CAKE_DL_RATE_KBPS: maybe replace CAKE with SHAPER and put the direction at first place: DL_SHAPER_KBPS?

All of these are fine as they are, but since you wanted me to look closely, I did ;)

**Comment by moeller0** [comment]
> So now I just use "; ", i.e. one space after the ";" - does that seem OK?

Yes, IMHO that makes things considerably more readable. (When I have to program I tend to add spaces around most operators for the same reason, better readability, "1 + 5^7 / (17 * 3)" reads easier than "1+5^7/(17*3)" (I keep exponents together as I tend to think of them more as a weird way of writing a number and less as an operation, I did not say I was consistent ;))

**Comment by lynxthecat** [comment]
Thanks for your help with the log file aspects here. I think these are terrific changes. And I think I'll just keep it running on my own system with 60 mins (up to 120 min with .old and current logs). 

Would you expect this to incur a performance hit or not really?

**Comment by moeller0** [comment]
> Would you expect this to incur a performance hit or not really?

Not really, maybe first delete the old .old logfile, then move (mv) the current log file to old then start the new one. But that seems to be in the margins, after all this runs by default once per hour, so even if would take a second, would we notice or care?

**Comment by patrakov** [comment]
Can we have microseconds in human-readable timestamps, too?

**Comment by lynxthecat** [comment]
What do you mean? Right now we have:

```
DATA; 2022-09-20-21:02:43; 1663704163.019317; 1663704163.018495; 113; 23; 0; 0; 1663704163.00775; 1.1.1.1; 5368; 36926; 47600; 10684; 26414; 0; dl_idle; ul_idle; 13409; 27339
DATA; 2022-09-20-21:02:43; 1663704163.064871; 1663704163.064054; 113; 23; 0; 0; 1663704163.05279; 1.0.0.1; 5368; 35102; 42500; 7405; 26414; 0; dl_idle; ul_idle; 13543; 27339
```

**Comment by patrakov** [comment]
I want `2022-09-20-21:02:43.019317` in the second column.

**Comment by patrakov** [comment]
```
log_msg()
{
	local type=$1
	local msg=$2
	local timestamp=$EPOCHREALTIME

	if [[ ! -t 1 ]]; then
	        printf '%s; %(%F-%H:%M:%S)T.%s; %s; %s\n' "$type" ${timestamp%.*} ${timestamp#*.} "$timestamp" "$msg" >> /tmp/cake-autorate.log
	else
	        printf '%s; %(%F-%H:%M:%S)T.%s; %s; %s\n' "$type" ${timestamp%.*} ${timestamp#*.} "$timestamp" "$msg"
	fi
}
```

**Comment by moeller0** [comment]
> I want `2022-09-20-21:02:43.019317` in the second column.

I specifically asked for the DATETIME to be a standard string that is easier to retranslate into e.g. matlab's internal date representation. For anything else the $EPOCHREALTIME is a better unambiguous timestamp. But then this is a matter of subjective preference and mine isn't any better (or worse) than yours...

**Comment by patrakov** [comment]
Look, I keep $EPOCHREALTIME as its own column (the third one).

```
DATA; 2022-09-21-07:05:46.149651; 1663743946.149651; 1663743946.149389; 55; 15; 0; 1; 1663743946.14548; 1.0.0.1; 691; 64638; 75000; 10372; 251544; 0; dl_idle; ul_idle; 6461; 1143
DATA; 2022-09-21-07:05:46.651503; 1663743946.651503; 1663743946.651251; 4; 2; 0; 0; 1663743946.64751; 8.8.8.8; 691; 60972; 76600; 15643; 251544; 0; dl_idle; ul_idle; 6461; 1143
DATA; 2022-09-21-07:05:47.150890; 1663743947.150890; 1663743947.150640; 9; 2; 0; 0; 1663743947.14650; 8.8.4.4; 691; 63419; 75100; 11692; 251544; 0; dl_idle; ul_idle; 6461; 1143
```

**Comment by moeller0** [comment]
Yes, but then keep the DATETIME column shorter and don't repeat the same 7 numbers twice in consecutive columns...
For me the only value of DATETIME is that I can easier correlate this to wall clock time so I might know what happened on my network at around a given time, honestly for that purpose even truncating to minutes will be sufficiently precise, adding fractional seconds there is not going to help me.

**Comment by patrakov** [comment]
Yes. For me the value of microseconds is due to the DEBUG lines. They allow distinguishing between related lines and lines that correspond to different events.

**Comment by lynxthecat** [comment]
Well yes DEBUG does that but is the reason you want microseconds tagged on to the clock because you find it easier that way to get an idea of deltas between lines? Since as @moeller0 points out this can already be worked out from the timestamps and we introduce redundancy by repeating the microseconds twice. Some might also argue it clutters the date.

**Comment by moeller0** [comment]
Sure, but the DEBUG lines also have DATETIME and TIMESTAMP, e.g.:
`DEBUG; 2022-09-20-10:42:59; 1663666979.225890; Starting CAKE-autorate 1.0.0`
unless I am missing something. My goal really is to converge on a log file that is easy to parse without any additional gymnastics and string manipulations...

**Comment by lynxthecat** [comment]
@patrakov you're a hard man to please 😄.

**Comment by lynxthecat** [comment]
BTW a cool thing with the logging now is that with running as a service anytime you want to see what's going on you can just issue 'tail -f /tmp/cake-autorate.log' and see what's happening.

**Comment by lynxthecat** [comment]
@moeller0/@patrakob since I no longer use:

exec &> /tmp/cake-autorate.log

Should I now redirect stderr with e.g.:

exec 2> /tmp/cake-autorate-stderr

Or something like that?

**Comment by lynxthecat** [comment]
Marking as complete since now use of 'fping' can be configured in the config, which fixes timing between the requests.
